/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-11-25 01:29:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/gyujin/approval/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/education/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1659671595531L));
    _jspx_dependants.put("jar:file:/D:/gyujin/approval/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/education/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>로그인</title>\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("     body {\n");
      out.write("     background-color: #F3EBF6;\n");
      out.write("     font-family: 'Ubuntu', sans-serif;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .main {\n");
      out.write("        background-color: #FFFFFF;\n");
      out.write("        width: 400px;\n");
      out.write("        height: 400px;\n");
      out.write("        margin: 7em auto;\n");
      out.write("        border-radius: 1.5em;\n");
      out.write("        box-shadow: 0px 11px 35px 2px rgba(0, 0, 0, 0.14);\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .sign {\n");
      out.write("        padding-top: 40px;\n");
      out.write("        color: #8C55AA;\n");
      out.write("        font-family: 'Ubuntu', sans-serif;\n");
      out.write("        font-weight: bold;\n");
      out.write("        font-size: 23px;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .un {\n");
      out.write("    width: 76%;\n");
      out.write("    color: rgb(38, 50, 56);\n");
      out.write("    font-weight: 700;\n");
      out.write("    font-size: 14px;\n");
      out.write("    letter-spacing: 1px;\n");
      out.write("    background: rgba(136, 126, 126, 0.04);\n");
      out.write("    padding: 10px 20px;\n");
      out.write("    border: none;\n");
      out.write("    border-radius: 20px;\n");
      out.write("    outline: none;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    border: 2px solid rgba(0, 0, 0, 0.02);\n");
      out.write("    margin-bottom: 50px;\n");
      out.write("    margin-left: 46px;\n");
      out.write("    text-align: center;\n");
      out.write("    margin-bottom: 27px;\n");
      out.write("    font-family: 'Ubuntu', sans-serif;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    form.form1 {\n");
      out.write("        padding-top: 40px;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .pass {\n");
      out.write("            width: 76%;\n");
      out.write("    color: rgb(38, 50, 56);\n");
      out.write("    font-weight: 700;\n");
      out.write("    font-size: 14px;\n");
      out.write("    letter-spacing: 1px;\n");
      out.write("    background: rgba(136, 126, 126, 0.04);\n");
      out.write("    padding: 10px 20px;\n");
      out.write("    border: none;\n");
      out.write("    border-radius: 20px;\n");
      out.write("    outline: none;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    border: 2px solid rgba(0, 0, 0, 0.02);\n");
      out.write("    margin-bottom: 50px;\n");
      out.write("    margin-left: 46px;\n");
      out.write("    text-align: center;\n");
      out.write("    margin-bottom: 27px;\n");
      out.write("    font-family: 'Ubuntu', sans-serif;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("   \n");
      out.write("    .un:focus, .pass:focus {\n");
      out.write("        border: 2px solid rgba(0, 0, 0, 0.18) !important;\n");
      out.write("        \n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .submit {\n");
      out.write("      cursor: pointer;\n");
      out.write("        border-radius: 5em;\n");
      out.write("        color: #fff;\n");
      out.write("        background: linear-gradient(to right, #9C27B0, #E040FB);\n");
      out.write("        border: 0;\n");
      out.write("        padding-left: 40px;\n");
      out.write("        padding-right: 40px;\n");
      out.write("        padding-bottom: 10px;\n");
      out.write("        padding-top: 10px;\n");
      out.write("        font-family: 'Ubuntu', sans-serif;\n");
      out.write("        margin-left: 35%;\n");
      out.write("        font-size: 13px;\n");
      out.write("        box-shadow: 0 0 20px 1px rgba(0, 0, 0, 0.04);\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .forgot {\n");
      out.write("        text-shadow: 0px 0px 3px rgba(117, 117, 117, 0.12);\n");
      out.write("        color: #E1BEE7;\n");
      out.write("        padding-top: 15px;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    a {\n");
      out.write("        text-shadow: 0px 0px 3px rgba(117, 117, 117, 0.12);\n");
      out.write("        color: #E1BEE7;\n");
      out.write("        text-decoration: none\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    @media (max-width: 600px) {\n");
      out.write("        .main {\n");
      out.write("            border-radius: 0px;\n");
      out.write("        }\n");
      out.write("  </style>  \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  \n");
      out.write("  <div class=\"main\">\n");
      out.write("    <p class=\"sign\" align=\"center\">Sign in</p>\n");
      out.write("    <form class=\"form1\"  id=\"fr\" method=\"POST\">\n");
      out.write("	      <input class=\"un \" type=\"text\"  name=\"userid\" id=\"userid\" align=\"center\" placeholder=\"USERNAME\" required>\n");
      out.write("	      <input class=\"pass\" type=\"password\" name=\"userpw\", id=\"userpw\" align=\"center\" placeholder=\"PASSWORD\" required>\n");
      out.write("	      <button class=\"submit\" type=\"button\" id=\"btn\">Sign in</button>\n");
      out.write("	      <p class=\"forgot\" align=\"center\"><a href=\"#\">Forgot Password?</a></p> \n");
      out.write("     </form>     \n");
      out.write("   </div>\n");
      out.write("   \n");
      out.write("   <script>\n");
      out.write("  	\n");
      out.write("   		\n");
      out.write("  		/* $(\"#btn\").click(function() {\n");
      out.write("  			var userid = $(\"#userid\").val();\n");
      out.write("  			var userpw = $(\"#userpw\").val();\n");
      out.write("  			\n");
      out.write("  			if(userid == \"\") {\n");
      out.write("  				alert(\"아이디를 입력하세요.\");\n");
      out.write("  				$(\"#userid\").focus();\n");
      out.write("  				\n");
      out.write("  			} else if(userpw == \"\") {  				\n");
      out.write("  				alert(\"비밀번호를 입력하세요.\");\n");
      out.write("  				$(\"#userpw\").focus(); 				\n");
      out.write("  			} else {\n");
      out.write("  				$(\"#fr\").attr(\"action\", \"member/loginCheck.do\").submit();\n");
      out.write("  			}\n");
      out.write("  			\n");
      out.write("  		})\n");
      out.write("  		\n");
      out.write(" 		$(function(){\n");
      out.write("  			var loginCheck = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginCheck}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("  			\n");
      out.write("  			if(loginCheck == 'useridFail') {\n");
      out.write("  				alert(\"등록 되어 있지 않는 아이디 입니다.\");\n");
      out.write("  				$(\"#uesrid\").focus();\n");
      out.write("  				\n");
      out.write("  			} else if(loginCheck == 'userpwFail') {\n");
      out.write("  				alert(\"비밀번호가 틀렸습니다.\");\n");
      out.write("  				$(\"#userpw\").focus();\n");
      out.write("  				\n");
      out.write("  			}  			 \n");
      out.write("  		}) */\n");
      out.write("  		\n");
      out.write("  		$(function(){\n");
      out.write("\n");
      out.write("			$(\"#btn\").click(function() {\n");
      out.write("  			var userid = $(\"#userid\").val();\n");
      out.write("  			var userpw = $(\"#userpw\").val();\n");
      out.write("  			\n");
      out.write("  			if(userid == \"\") {\n");
      out.write("  				alert(\"아이디를 입력하세요.\");\n");
      out.write("  				$(\"#userid\").focus();\n");
      out.write("  				\n");
      out.write("  			} else if(userpw == \"\") {  				\n");
      out.write("  				alert(\"비밀번호를 입력하세요.\");\n");
      out.write("  				$(\"#userpw\").focus(); 				\n");
      out.write("  			} else {\n");
      out.write("  				$(\"#fr\").attr(\"action\", \"member/loginCheck.do\").submit();\n");
      out.write("  			}\n");
      out.write("  			\n");
      out.write("  		})\n");
      out.write("  			var loginCheck = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginCheck}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("  			\n");
      out.write("  			if(loginCheck == 'useridFail') {\n");
      out.write("  				alert(\"등록 되어 있지 않는 아이디 입니다.\");\n");
      out.write("  				$(\"#uesrid\").focus();\n");
      out.write("  				\n");
      out.write("  			} else if(loginCheck == 'userpwFail') {\n");
      out.write("  				alert(\"비밀번호가 틀렸습니다.\");\n");
      out.write("  				$(\"#userpw\").focus();\n");
      out.write("  				\n");
      out.write("  			}  			 \n");
      out.write("  		})\n");
      out.write("  		\n");
      out.write("  		\n");
      out.write("  		\n");
      out.write("  		\n");
      out.write("  		\n");
      out.write("  </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
